### ISSUE TITLE
blank page?

### ISSUE THREAD

**Issue by onthemdrugs** [JadedCtrl/insert-coin#3]
Just wondering after deploying and changing the stuff said in the README, what version of PHP does this use?

**Comment by JadedCtrl** [comment]
It looks like this was the result of a bug, I just fixed it: 37c4ce18f24cd9e8b9fb10edb238b9ba55888d44.

I’ve just tested insert-coin on PHP 8.3.2; after fixing this bug, it seems to work fine. ^^

**Comment by JadedCtrl** [comment]
I think this might be the result of a typo I just fixed: 37c4ce18f24cd9e8b9fb10edb238b9ba55888d44.

Having fixed that typo, insert-coin seems to work fine on PHP 8.3.2. ^^

**Comment by onthemdrugs** [comment]
works a treat now, thank you!

**Comment by onthemdrugs** [comment]
I do have to ask is there anywhere to change what filetypes can be uploaded?

I just tried a mp3 and it said something about directory permissions although everything else worked.

Thanks :)

**Comment by onthemdrugs** [comment]
Fixed //
